### ISSUE TITLE
[Feature Request] Adding ARM support for Docker images 

### ISSUE THREAD

**Issue by conradkirschner** [fabieu/sureflap-api#4]
Story:
Some people would like to use ARM Architecture to run the sureflap-api docker container. (e.g. Raspberry Pi) 

Therefore I would like to have a Docker Image for ARM Architecture.

**Comment by conradkirschner** [comment]
https://hub.docker.com/r/arm64v8/python/

**Comment by fabieu** [comment]
https://docs.docker.com/engine/reference/commandline/build/

**Comment by conradkirschner** [comment]
> https://docs.docker.com/engine/reference/commandline/build/

Thought more about adding this to the pipeline, so not everyone has to rebuild it and it's always up-to-date, but not sure how you sync this repo with gitlab.  

Not sure if a PR would make sense here.

**Comment by fabieu** [comment]
I am going to add ARM support in the future. No worries. 
You can actually mirror the entire repository to GitLab, but this reference is currently inactive. 

Thanks for the PR.

**Comment by conradkirschner** [comment]
ah okay, I thought that you have a private/other gitlab instance where you set a mirror to github. 

got confused by the gitlab file 
As I don't have access to the repo (so not sure if you added already docker hub credentials) 

This might be helpful 
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by fabieu** [comment]
@conradkirschner You can now find prebuild images for amd64, arm64 and arm32 on DockerHub: https://hub.docker.com/repository/docker/fabieu/sureflap-api
