### ISSUE TITLE
Time difference of 5 minutes

### ISSUE THREAD

**Issue by alphatrianguli** [fabieu/sureflap-api#48]
I have been noticing for quite some time, that I have a time deviation / difference between the actual time when my pets leave or enter the house through the pet door and the time, that the API returns. The time in the official SurePet App is correct, while the API returns a time stamp which is about 4-5 minutes earlier. 

I already checked the time inside the docker container with `docker exec -it surehub-api date` and it returns the correct current time.

Anybody have an idea? Hints are much appreciated! :)

**Comment by fabieu** [comment]
A few minutes earlier seems very strange. I will have a look and try to reproduce this by myself.

**Comment by alphatrianguli** [comment]
It is indeed very strange. So when the cat comes in at 2:00 pm for example, the API shows 1:55 pm.

Interestingly, when changing the cat location manually via the SurePet app, the time is correct. So the time only seems to be off, when it is changed by the cat using the door.

**Comment by fabieu** [comment]
> It is indeed very strange. So when the cat comes in at 2:00 pm for example, the API shows 1:55 pm.
> 
> Interestingly, when changing the cat location manually via the SurePet app, the time is correct. So the time only seems to be off, when it is changed by the cat using the door.

Unfortunatly I was not able to reproduce the issue. I checked the time when my cats went through the cat flap. The time returned by the API is accurate to the second. Since I query the official SureHub API directly, there is nothing I can do about the inaccuracy you described.

If it's okay with you, I would close the issue.
